# Generated by Django 4.1.3 on 2022-12-01 00:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name = 'Profile',
            fields = [
                ('id', models.BigAutoField(auto_created = True, primary_key = True, serialize = False, verbose_name = 'ID')),
                ('student_number', models.CharField(max_length = 10, null = True)),
                ('share_timetable', models.BooleanField(default = False)),
                ('user', models.OneToOneField(on_delete = django.db.models.deletion.CASCADE, to = settings.AUTH_USER_MODEL)),
            ],
            options = {
                'db_table': 'user_extended',
            },
        ),
    ]
