# Generated by Django 4.1.3 on 2022-12-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name = 'profile',
            name = 'share_timetable',
        ),
        migrations.AddField(
            model_name = 'profile',
            name = 'degree',
            field = models.CharField(choices = [('석사', 'Master'), ('박사', 'Combined'), ('통합', 'Ph.D')], default = '석사', max_length = 10),
        ),
        migrations.AddField(
            model_name = 'profile',
            name = 'passed',
            field = models.JSONField(default = {}),
        ),
    ]
