# Generated by Django 4.1.3 on 2022-12-01 22:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_profile_share_timetable_profile_degree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name = 'profile',
            name = 'uploaded_at',
            field = models.DateTimeField(auto_now_add = True, default = django.utils.timezone.now),
            preserve_default = False,
        ),
        migrations.AlterField(
            model_name = 'profile',
            name = 'passed',
            field = models.JSONField(default = dict),
        ),
    ]
