# Generated by Django 4.1.3 on 2022-12-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_profile_include_undergrad'),
    ]

    operations = [
        migrations.AddField(
            model_name = 'profile',
            name = 'share_timetable',
            field = models.BooleanField(default = False),
        ),
    ]
