# Generated by Django 4.1.3 on 2022-12-04 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0005_profile_share_timetable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name = 'profile',
            name = 'id',
        ),
        migrations.AlterField(
            model_name = 'profile',
            name = 'user',
            field = models.OneToOneField(on_delete = django.db.models.deletion.CASCADE, primary_key = True, serialize = False, to = settings.AUTH_USER_MODEL),
        ),
    ]
