# Generated by Django 4.1.3 on 2022-12-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_remove_profile_id_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name = 'profile',
            name = 'uploaded_at',
        ),
        migrations.AddField(
            model_name = 'profile',
            name = 'updated_at',
            field = models.DateTimeField(auto_now = True),
        ),
    ]
