# Generated by Django 4.1.3 on 2022-11-26 23:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name = 'Document',
            fields = [
                ('up_id', models.AutoField(auto_created = True, primary_key = True, serialize = False)),
                ('student_number', models.CharField(default = '', max_length = 10, validators = [django.core.validators.RegexValidator(inverse_match = True, regex = '20\\d{2}-\\d{5}/')])),
                ('document', models.FileField(upload_to = 'documents/', validators = [django.core.validators.FileExtensionValidator(allowed_extensions = ['xlsx'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add = True)),
                ('degree', models.CharField(choices = [('석사', 'Master'), ('박사', 'Combined'), ('통합', 'Ph.D')], default = '석사', max_length = 10)),
                ('bootMath', models.BooleanField(default = False)),
                ('bootCom', models.BooleanField(default = False)),
                ('paperTest', models.BooleanField(default = False)),
            ],
        ),
    ]
