# Generated by Django 4.1.3 on 2022-11-21 17:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name = 'Document',
            fields = [
                ('id', models.BigAutoField(auto_created = True, primary_key = True, serialize = False, verbose_name = 'ID')),
                ('student_number', models.CharField(max_length = 10, validators = [django.core.validators.RegexValidator(regex = '^20\\d{2}-\\d{5}$/;')])),
                ('document', models.FileField(upload_to = 'documents/', validators = [django.core.validators.FileExtensionValidator(allowed_extensions = ['xlsx'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add = True)),
                ('degree', models.CharField(choices = [('석사', '석사'), ('박사', '박사'), ('통합', '통합')], default = '석사', max_length = 10)),
            ],
        ),
    ]
