# Generated by Django 4.1.3 on 2022-12-01 15:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name = 'Document',
            fields = [
                ('up_id', models.AutoField(auto_created = True, primary_key = True, serialize = False)),
                ('student_number', models.CharField(default = '', max_length = 10, validators = [django.core.validators.RegexValidator(inverse_match = True, regex = '20\\d{2}-\\d{5}/')])),
                ('document', models.FileField(upload_to = 'documents/', validators = [django.core.validators.FileExtensionValidator(allowed_extensions = ['xlsx'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add = True)),
                ('updated_at', models.DateTimeField(auto_now = True)),
                ('degree', models.CharField(choices = [('석사', 'Master'), ('박사', 'Combined'), ('통합', 'Ph.D')], default = '석사', max_length = 10)),
                ('boot_math', models.BooleanField(default = False)),
                ('boot_com', models.BooleanField(default = False)),
                ('paper_test', models.BooleanField(default = False)),
                ('share_yn', models.BooleanField(default = False)),
                ('user', models.ForeignKey(on_delete = django.db.models.deletion.CASCADE, to = settings.AUTH_USER_MODEL, verbose_name = 'user')),
            ],
        ),
    ]
