# Generated by Django 4.1.3 on 2022-11-21 17:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelupload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name = 'document',
            name = 'student_number',
            field = models.CharField(max_length = 10, validators = [django.core.validators.RegexValidator(regex = '^20\\d{2}-\\d{5}$/')]),
        ),
    ]
