# Generated by Django 4.1.3 on 2022-12-04 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excelupload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name = 'document',
            name = 'share_yn',
        ),
    ]
