# Generated by Django 4.1.3 on 2022-11-26 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excelupload', '0002_document_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name = 'document',
            old_name = 'bootCom',
            new_name = 'boot_com',
        ),
        migrations.RenameField(
            model_name = 'document',
            old_name = 'bootMath',
            new_name = 'boot_math',
        ),
        migrations.RenameField(
            model_name = 'document',
            old_name = 'paperTest',
            new_name = 'paper_test',
        ),
        migrations.RenameField(
            model_name = 'document',
            old_name = 'user_id',
            new_name = 'user',
        ),
    ]
