# Generated by Django 4.1.3 on 2022-11-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelupload', '0003_rename_bootcom_document_boot_com_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name = 'document',
            name = 'updated_at',
            field = models.DateTimeField(auto_now = True),
        ),
    ]
