# Generated by Django 4.1.3 on 2022-11-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelupload', '0004_alter_document_student_number'),
    ]

    operations = [
        migrations.AddField(
            model_name = 'document',
            name = 'bootCom',
            field = models.BooleanField(default = False),
        ),
        migrations.AddField(
            model_name = 'document',
            name = 'bootMath',
            field = models.BooleanField(default = False),
        ),
    ]
