# Generated by Django 4.1.3 on 2022-11-23 17:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelupload', '0005_document_bootcom_document_bootmath'),
    ]

    operations = [
        migrations.AlterField(
            model_name = 'document',
            name = 'student_number',
            field = models.CharField(default = '', max_length = 10, validators = [django.core.validators.RegexValidator(inverse_match = True, regex = '20\\d{2}-\\d{5}/')]),
        ),
    ]
