# Generated by Django 4.1.3 on 2022-11-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelupload', '0007_document_papertest'),
    ]

    operations = [
        migrations.AlterField(
            model_name = 'document',
            name = 'degree',
            field = models.CharField(choices = [('석사', 'Master'), ('박사', 'Combined'), ('통합', 'Ph.d')], default = '석사', max_length = 10),
        ),
    ]
