# Generated by Django 4.1.3 on 2022-12-02 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name = 'courses',
            options = {'managed': True},
        ),
    ]
