# Generated by Django 4.1.3 on 2022-12-03 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0001_initial'),
        ('recommendation', '0002_alter_courses_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name = 'courses',
            name = 'cid',
            field = models.OneToOneField(db_column = 'cid', on_delete = django.db.models.deletion.CASCADE, primary_key = True, serialize = False, to = 'check.coursekey'),
        ),
        migrations.AlterField(
            model_name = 'courses',
            name = 'last_yr_sem',
            field = models.CharField(blank = True, max_length = 10, null = True),
        ),
        migrations.AlterModelTable(
            name = 'recommendedresult',
            table = '',
        ),
    ]
